### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by AlexScigalszky** [AlexScigalszky/qa#3]

**Comment by AlexScigalszky** [comment]
Explain the rules of Pull Requests:
* must compile
* the command `npm run prittier:fix` must be executed

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me, I'll do it.

**Comment by mohitsaxenaknoldus** [comment]
Added PR: https://github.com/AlexScigalszky/qa/pull/9
Please review @AlexScigalszky
